aircraft_configs:
  A0100:
    color: Red
    init_state:
      ic_h_sl_ft: 30000
      ic_lat_geod_deg: 60.0
      ic_long_gc_deg: 120.6757
      ic_psi_true_deg: 0.0
      ic_u_fps: 1251.1
    missile: 4
    model: su27sk
  A0200:
    color: Red
    init_state:
      ic_h_sl_ft: 30000
      ic_lat_geod_deg: 60.2009
      ic_long_gc_deg: 120.4252
      ic_psi_true_deg: 180.0
      ic_u_fps: 1251.1
    missile: 4
    model: su27sk
  A0300:
    color: Red
    init_state:
      ic_h_sl_ft: 30000
      ic_lat_geod_deg: 60.0
      ic_long_gc_deg: 121.3766
      ic_psi_true_deg: 0.0
      ic_u_fps: 1251.1
    missile: 4
    model: su27sk
  A0400:
    color: Red
    init_state:
      ic_h_sl_ft: 30000
      ic_lat_geod_deg: 60.2009
      ic_long_gc_deg: 121.1261
      ic_psi_true_deg: 180.0
      ic_u_fps: 1251.1
    missile: 4
    model: su27sk
  B0100:
    color: Blue
    init_state:
      ic_h_sl_ft: 30000.00096
      ic_lat_geod_deg: 62.252252252252255
      ic_long_gc_deg: 119.90993423423424
      ic_psi_true_deg: 180
      ic_u_fps: 1251.1
    missile: 4
    model: f16
  B0200:
    color: Blue
    init_state:
      ic_h_sl_ft: 30000.00096
      ic_lat_geod_deg: 62.252252252252255
      ic_long_gc_deg: 120.09011441441442
      ic_psi_true_deg: 180
      ic_u_fps: 1251.1
    missile: 4
    model: f16
  B0300:
    color: Blue
    init_state:
      ic_h_sl_ft: 30000.00096
      ic_lat_geod_deg: 62.16216216216216
      ic_long_gc_deg: 119.90993423423424
      ic_psi_true_deg: 180
      ic_u_fps: 1251.1
    missile: 4
    model: f16
  B0400:
    color: Blue
    init_state:
      ic_h_sl_ft: 30000.00096
      ic_lat_geod_deg: 62.16216216216216
      ic_long_gc_deg: 120.09011441441442
      ic_psi_true_deg: 180
      ic_u_fps: 1251.1
    missile: 4
    model: f16
base_reference:
  a0100:
    heading: 0.0
    latitude: 60.0
    longitude: 120.6757
enemy:
  spawn_x:
  - 40
  - 80
  - 120
  - 160
  spawn_y: 250.0
formation:
  lead_x:
    left: 75.0
    right: 125.0
  wingman_x:
    left: 25.0
    right: 175.0
  wingman_y_offset: 100.0
max_steps: 10000
task: multiplecombat
time_interval: 0.2
