"""Compatibility wrapper for the refactored radar manager."""

from .radar_manager_impl import (
    APG68RadarModel,
    ECMType,
    N001VERadarModel,
    RadarManager,
    RadarStatus,
    RadarTarget,
    UnifiedRadarManager,
    check_missile_launch_conditions,
    get_enemy_lock_target,
    get_enemy_radar_data,
    get_enemy_radar_state,
    get_enemy_radar_states,
    get_enemy_radar_targets,
    get_friendly_radar_state,
    get_friendly_radar_states,
    get_jamming_sources,
    get_radar_manager,
    get_radar_performance_summary,
    get_rwr_max_threat_bearing,
    get_rwr_threat_level,
    get_rwr_threat_sources,
    get_unified_radar_manager,
    is_being_jammed,
    is_enemy_ecm_active,
    update_all_radars,
)

__all__ = [
    "APG68RadarModel",
    "ECMType",
    "N001VERadarModel",
    "RadarManager",
    "RadarStatus",
    "RadarTarget",
    "UnifiedRadarManager",
    "check_missile_launch_conditions",
    "get_enemy_lock_target",
    "get_enemy_radar_data",
    "get_enemy_radar_state",
    "get_enemy_radar_states",
    "get_enemy_radar_targets",
    "get_friendly_radar_state",
    "get_friendly_radar_states",
    "get_jamming_sources",
    "get_radar_manager",
    "get_radar_performance_summary",
    "get_rwr_max_threat_bearing",
    "get_rwr_threat_level",
    "get_rwr_threat_sources",
    "get_unified_radar_manager",
    "is_being_jammed",
    "is_enemy_ecm_active",
    "update_all_radars",
]
